version: '3.1'

services:
  app:
    build:
      context: "."
      args:
        - UID
        - GID
        - USERNAME=croaker
        - GROUPNAME=croaker
    tty: true
    volumes:
      - ".:/srv"
    # command: sh -c "npm run dev"
    environment:
      TZ: Asia/Tokyo
      NODE_ENV: develop
      PORT: 3000
      SQLITE_FILE: croaker.sqlite3 # TODO
      GOOGLE_CLOUD_PROJECT: '' # TODO
      GOOGLE_CLOUD_KEY: './key.json' # TODO
      STORAGE_BUCKET: '' # TODO
      STORAGE_DIRECTORY: '' # TODO
      # SESSION_SECRET: secret12secret34secret56secret78
      # SESSION_COOKIE_NAME: session-id
      NEXTAUTH_SECRET: "something_secret"
      NEXTAUTH_URL: "http://localhost:3000"
      GITHUB_ID: "" # TODO
      GITHUB_SECRET: "" # TODO
      GOOGLE_CLIENT_ID: "" # TODO
      GOOGLE_CLIENT_SECRET: "" # TODO
    ports:
      - "3000:3000"
